[package]
name = "cryxtal-derivers"
version = "0.1.0"
edition = "2021"
description = "Derive macros generating an impl of the geometric traits."

[lib]
proc-macro = true

[dependencies]
quote = "1.0.40"
proc-macro2 = "1.0.101"
syn = { version = "2.0.106", features = ["derive", "printing"] }
proc-macro-error = "1.0.4"
